### ISSUE TITLE
Modifications to VU009 (and perhaps other modules)

### ISSUE THREAD

**Issue by analogmonster** [Syntonie/documentation#3]
Just noticed the modifications for VU003B.  Should these mods be applied to VU009?  IE R26 should be a 1/2 watt 75 ohm resistor and R29 should be a 1/4 watt 47 ohm resistor.  I expect the 75 ohm mod apllies to any output that you want to improve for working in HD for basically any manufacturer.  Time to stock up on 1/2 watt 75 ohm resistors

**Comment by Syntonie** [comment]
About the 75R output resistors, I think it makes the most sense to do the modification for processor circuits rather than generators, as VU009 goes up to ~1MHz, changing the resistor might make the hard edge of the sawtooth a bit sharper, though it might be limited by the circuit itself and not the output resistor. For the chroma filter resistor, it didn't seems to cause an issue with VU009, as it syncs correctly in all HD formats with the original resistor value.

And more generally, I made the modification documentation for VU003B as it claims to support HD, whereas all the other VU released previously were made at a time where there was no HD encoder/sync generator, then of course, definitely possible to modify them to have a higher bandwidth. Might emphasize some artefacts that may have not be too visible before though, then DIY is all about experiment!
